/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUuidGeneratorRouteImport } from './routes/tools/uuid-generator'
import { Route as ToolsUrlParserRouteImport } from './routes/tools/url-parser'
import { Route as ToolsUnixTimestampRouteImport } from './routes/tools/unix-timestamp'
import { Route as ToolsStringInspectorRouteImport } from './routes/tools/string-inspector'
import { Route as ToolsSecretGeneratorRouteImport } from './routes/tools/secret-generator'
import { Route as ToolsRegexRouteImport } from './routes/tools/regex'
import { Route as ToolsQrCodeRouteImport } from './routes/tools/qr-code'
import { Route as ToolsPaletteRouteImport } from './routes/tools/palette'
import { Route as ToolsMarkdownRouteImport } from './routes/tools/markdown'
import { Route as ToolsJwtRouteImport } from './routes/tools/jwt'
import { Route as ToolsJsonFormatterRouteImport } from './routes/tools/json-formatter'
import { Route as ToolsHmacRouteImport } from './routes/tools/hmac'
import { Route as ToolsHashRouteImport } from './routes/tools/hash'
import { Route as ToolsGradientRouteImport } from './routes/tools/gradient'
import { Route as ToolsDiffRouteImport } from './routes/tools/diff'
import { Route as ToolsDataConverterRouteImport } from './routes/tools/data-converter'
import { Route as ToolsCronRouteImport } from './routes/tools/cron'
import { Route as ToolsColorsRouteImport } from './routes/tools/colors'
import { Route as ToolsCodeFormatterRouteImport } from './routes/tools/code-formatter'
import { Route as ToolsClockRouteImport } from './routes/tools/clock'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidGeneratorRoute = ToolsUuidGeneratorRouteImport.update({
  id: '/tools/uuid-generator',
  path: '/tools/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUrlParserRoute = ToolsUrlParserRouteImport.update({
  id: '/tools/url-parser',
  path: '/tools/url-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUnixTimestampRoute = ToolsUnixTimestampRouteImport.update({
  id: '/tools/unix-timestamp',
  path: '/tools/unix-timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsStringInspectorRoute = ToolsStringInspectorRouteImport.update({
  id: '/tools/string-inspector',
  path: '/tools/string-inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSecretGeneratorRoute = ToolsSecretGeneratorRouteImport.update({
  id: '/tools/secret-generator',
  path: '/tools/secret-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRegexRoute = ToolsRegexRouteImport.update({
  id: '/tools/regex',
  path: '/tools/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrCodeRoute = ToolsQrCodeRouteImport.update({
  id: '/tools/qr-code',
  path: '/tools/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPaletteRoute = ToolsPaletteRouteImport.update({
  id: '/tools/palette',
  path: '/tools/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMarkdownRoute = ToolsMarkdownRouteImport.update({
  id: '/tools/markdown',
  path: '/tools/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJwtRoute = ToolsJwtRouteImport.update({
  id: '/tools/jwt',
  path: '/tools/jwt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonFormatterRoute = ToolsJsonFormatterRouteImport.update({
  id: '/tools/json-formatter',
  path: '/tools/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHmacRoute = ToolsHmacRouteImport.update({
  id: '/tools/hmac',
  path: '/tools/hmac',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashRoute = ToolsHashRouteImport.update({
  id: '/tools/hash',
  path: '/tools/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGradientRoute = ToolsGradientRouteImport.update({
  id: '/tools/gradient',
  path: '/tools/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiffRoute = ToolsDiffRouteImport.update({
  id: '/tools/diff',
  path: '/tools/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDataConverterRoute = ToolsDataConverterRouteImport.update({
  id: '/tools/data-converter',
  path: '/tools/data-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronRoute = ToolsCronRouteImport.update({
  id: '/tools/cron',
  path: '/tools/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorsRoute = ToolsColorsRouteImport.update({
  id: '/tools/colors',
  path: '/tools/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCodeFormatterRoute = ToolsCodeFormatterRouteImport.update({
  id: '/tools/code-formatter',
  path: '/tools/code-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsClockRoute = ToolsClockRouteImport.update({
  id: '/tools/clock',
  path: '/tools/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/clock': typeof ToolsClockRoute
  '/tools/code-formatter': typeof ToolsCodeFormatterRoute
  '/tools/colors': typeof ToolsColorsRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/data-converter': typeof ToolsDataConverterRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/markdown': typeof ToolsMarkdownRoute
  '/tools/palette': typeof ToolsPaletteRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/secret-generator': typeof ToolsSecretGeneratorRoute
  '/tools/string-inspector': typeof ToolsStringInspectorRoute
  '/tools/unix-timestamp': typeof ToolsUnixTimestampRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/clock': typeof ToolsClockRoute
  '/tools/code-formatter': typeof ToolsCodeFormatterRoute
  '/tools/colors': typeof ToolsColorsRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/data-converter': typeof ToolsDataConverterRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/markdown': typeof ToolsMarkdownRoute
  '/tools/palette': typeof ToolsPaletteRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/secret-generator': typeof ToolsSecretGeneratorRoute
  '/tools/string-inspector': typeof ToolsStringInspectorRoute
  '/tools/unix-timestamp': typeof ToolsUnixTimestampRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/clock': typeof ToolsClockRoute
  '/tools/code-formatter': typeof ToolsCodeFormatterRoute
  '/tools/colors': typeof ToolsColorsRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/data-converter': typeof ToolsDataConverterRoute
  '/tools/diff': typeof ToolsDiffRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/hmac': typeof ToolsHmacRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/jwt': typeof ToolsJwtRoute
  '/tools/markdown': typeof ToolsMarkdownRoute
  '/tools/palette': typeof ToolsPaletteRoute
  '/tools/qr-code': typeof ToolsQrCodeRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/secret-generator': typeof ToolsSecretGeneratorRoute
  '/tools/string-inspector': typeof ToolsStringInspectorRoute
  '/tools/unix-timestamp': typeof ToolsUnixTimestampRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tools/base64'
    | '/tools/clock'
    | '/tools/code-formatter'
    | '/tools/colors'
    | '/tools/cron'
    | '/tools/data-converter'
    | '/tools/diff'
    | '/tools/gradient'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/json-formatter'
    | '/tools/jwt'
    | '/tools/markdown'
    | '/tools/palette'
    | '/tools/qr-code'
    | '/tools/regex'
    | '/tools/secret-generator'
    | '/tools/string-inspector'
    | '/tools/unix-timestamp'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tools/base64'
    | '/tools/clock'
    | '/tools/code-formatter'
    | '/tools/colors'
    | '/tools/cron'
    | '/tools/data-converter'
    | '/tools/diff'
    | '/tools/gradient'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/json-formatter'
    | '/tools/jwt'
    | '/tools/markdown'
    | '/tools/palette'
    | '/tools/qr-code'
    | '/tools/regex'
    | '/tools/secret-generator'
    | '/tools/string-inspector'
    | '/tools/unix-timestamp'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tools/base64'
    | '/tools/clock'
    | '/tools/code-formatter'
    | '/tools/colors'
    | '/tools/cron'
    | '/tools/data-converter'
    | '/tools/diff'
    | '/tools/gradient'
    | '/tools/hash'
    | '/tools/hmac'
    | '/tools/json-formatter'
    | '/tools/jwt'
    | '/tools/markdown'
    | '/tools/palette'
    | '/tools/qr-code'
    | '/tools/regex'
    | '/tools/secret-generator'
    | '/tools/string-inspector'
    | '/tools/unix-timestamp'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsClockRoute: typeof ToolsClockRoute
  ToolsCodeFormatterRoute: typeof ToolsCodeFormatterRoute
  ToolsColorsRoute: typeof ToolsColorsRoute
  ToolsCronRoute: typeof ToolsCronRoute
  ToolsDataConverterRoute: typeof ToolsDataConverterRoute
  ToolsDiffRoute: typeof ToolsDiffRoute
  ToolsGradientRoute: typeof ToolsGradientRoute
  ToolsHashRoute: typeof ToolsHashRoute
  ToolsHmacRoute: typeof ToolsHmacRoute
  ToolsJsonFormatterRoute: typeof ToolsJsonFormatterRoute
  ToolsJwtRoute: typeof ToolsJwtRoute
  ToolsMarkdownRoute: typeof ToolsMarkdownRoute
  ToolsPaletteRoute: typeof ToolsPaletteRoute
  ToolsQrCodeRoute: typeof ToolsQrCodeRoute
  ToolsRegexRoute: typeof ToolsRegexRoute
  ToolsSecretGeneratorRoute: typeof ToolsSecretGeneratorRoute
  ToolsStringInspectorRoute: typeof ToolsStringInspectorRoute
  ToolsUnixTimestampRoute: typeof ToolsUnixTimestampRoute
  ToolsUrlParserRoute: typeof ToolsUrlParserRoute
  ToolsUuidGeneratorRoute: typeof ToolsUuidGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid-generator': {
      id: '/tools/uuid-generator'
      path: '/tools/uuid-generator'
      fullPath: '/tools/uuid-generator'
      preLoaderRoute: typeof ToolsUuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/url-parser': {
      id: '/tools/url-parser'
      path: '/tools/url-parser'
      fullPath: '/tools/url-parser'
      preLoaderRoute: typeof ToolsUrlParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/unix-timestamp': {
      id: '/tools/unix-timestamp'
      path: '/tools/unix-timestamp'
      fullPath: '/tools/unix-timestamp'
      preLoaderRoute: typeof ToolsUnixTimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/string-inspector': {
      id: '/tools/string-inspector'
      path: '/tools/string-inspector'
      fullPath: '/tools/string-inspector'
      preLoaderRoute: typeof ToolsStringInspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/secret-generator': {
      id: '/tools/secret-generator'
      path: '/tools/secret-generator'
      fullPath: '/tools/secret-generator'
      preLoaderRoute: typeof ToolsSecretGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/regex': {
      id: '/tools/regex'
      path: '/tools/regex'
      fullPath: '/tools/regex'
      preLoaderRoute: typeof ToolsRegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-code': {
      id: '/tools/qr-code'
      path: '/tools/qr-code'
      fullPath: '/tools/qr-code'
      preLoaderRoute: typeof ToolsQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/palette': {
      id: '/tools/palette'
      path: '/tools/palette'
      fullPath: '/tools/palette'
      preLoaderRoute: typeof ToolsPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/markdown': {
      id: '/tools/markdown'
      path: '/tools/markdown'
      fullPath: '/tools/markdown'
      preLoaderRoute: typeof ToolsMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jwt': {
      id: '/tools/jwt'
      path: '/tools/jwt'
      fullPath: '/tools/jwt'
      preLoaderRoute: typeof ToolsJwtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-formatter': {
      id: '/tools/json-formatter'
      path: '/tools/json-formatter'
      fullPath: '/tools/json-formatter'
      preLoaderRoute: typeof ToolsJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hmac': {
      id: '/tools/hmac'
      path: '/tools/hmac'
      fullPath: '/tools/hmac'
      preLoaderRoute: typeof ToolsHmacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash': {
      id: '/tools/hash'
      path: '/tools/hash'
      fullPath: '/tools/hash'
      preLoaderRoute: typeof ToolsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/gradient': {
      id: '/tools/gradient'
      path: '/tools/gradient'
      fullPath: '/tools/gradient'
      preLoaderRoute: typeof ToolsGradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/diff': {
      id: '/tools/diff'
      path: '/tools/diff'
      fullPath: '/tools/diff'
      preLoaderRoute: typeof ToolsDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/data-converter': {
      id: '/tools/data-converter'
      path: '/tools/data-converter'
      fullPath: '/tools/data-converter'
      preLoaderRoute: typeof ToolsDataConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron': {
      id: '/tools/cron'
      path: '/tools/cron'
      fullPath: '/tools/cron'
      preLoaderRoute: typeof ToolsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/colors': {
      id: '/tools/colors'
      path: '/tools/colors'
      fullPath: '/tools/colors'
      preLoaderRoute: typeof ToolsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/code-formatter': {
      id: '/tools/code-formatter'
      path: '/tools/code-formatter'
      fullPath: '/tools/code-formatter'
      preLoaderRoute: typeof ToolsCodeFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/clock': {
      id: '/tools/clock'
      path: '/tools/clock'
      fullPath: '/tools/clock'
      preLoaderRoute: typeof ToolsClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsClockRoute: ToolsClockRoute,
  ToolsCodeFormatterRoute: ToolsCodeFormatterRoute,
  ToolsColorsRoute: ToolsColorsRoute,
  ToolsCronRoute: ToolsCronRoute,
  ToolsDataConverterRoute: ToolsDataConverterRoute,
  ToolsDiffRoute: ToolsDiffRoute,
  ToolsGradientRoute: ToolsGradientRoute,
  ToolsHashRoute: ToolsHashRoute,
  ToolsHmacRoute: ToolsHmacRoute,
  ToolsJsonFormatterRoute: ToolsJsonFormatterRoute,
  ToolsJwtRoute: ToolsJwtRoute,
  ToolsMarkdownRoute: ToolsMarkdownRoute,
  ToolsPaletteRoute: ToolsPaletteRoute,
  ToolsQrCodeRoute: ToolsQrCodeRoute,
  ToolsRegexRoute: ToolsRegexRoute,
  ToolsSecretGeneratorRoute: ToolsSecretGeneratorRoute,
  ToolsStringInspectorRoute: ToolsStringInspectorRoute,
  ToolsUnixTimestampRoute: ToolsUnixTimestampRoute,
  ToolsUrlParserRoute: ToolsUrlParserRoute,
  ToolsUuidGeneratorRoute: ToolsUuidGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
